const format = (str, value0, value1) => {
  return str.replace(/{0}/g, value0).replace(/{1}/g, value1);
}

const WOOD = [
        'minecraft:{0}oak_{1}',
        'minecraft:{0}birch_{1}',
        'minecraft:{0}spruce_{1}',
        'minecraft:{0}jungle_{1}',
        'minecraft:{0}acacia_{1}',
        'minecraft:{0}dark_oak_{1}',
        'minecraft:{0}mangrove_{1}',
        'minecraft:{0}cherry_{1}',
        'biomesoplenty:{0}fir_{1}',
        'biomesoplenty:{0}pine_{1}',
        'biomesoplenty:{0}maple_{1}',
        'biomesoplenty:{0}redwood_{1}',
        'biomesoplenty:{0}mahogany_{1}',
        'biomesoplenty:{0}jacaranda_{1}',
        'biomesoplenty:{0}palm_{1}',
        'biomesoplenty:{0}willow_{1}',
        'biomesoplenty:{0}dead_{1}',
        'biomesoplenty:{0}magic_{1}',
        'biomesoplenty:{0}umbran_{1}',
        'biomesoplenty:{0}hellbark_{1}',
        'biomesoplenty:{0}empyreal_{1}',
        'divinerpg:{0}divine_{1}',
        'divinerpg:{0}shiverspine_{1}',
        'divinerpg:{0}auroraoak_{1}',
        'divinerpg:{0}cozybark_{1}',
        'divinerpg:{0}streamleaf_{1}',
        'divinerpg:{0}eucalyptus_{1}',
        'divinerpg:{0}eden_{1}',
        'divinerpg:{0}wildwood_{1}',
        'divinerpg:{0}apalachia_{1}',
        'divinerpg:{0}skythern_{1}',
        'divinerpg:{0}apalachia_{1}',
        'divinerpg:{0}mortum_{1}',
        'twilightforest:{0}twilight_oak_{1}',
        'twilightforest:{0}canopy_{1}',
        'twilightforest:{0}mangrove_{1}',
        'twilightforest:{0}dark_{1}',
        'twilightforest:{0}time_{1}',
        'twilightforest:{0}transformation_{1}',
        'twilightforest:{0}mining_{1}',
        'twilightforest:{0}sorting_{1}',
    ];
  
const DYE = [
  'white',
  'light_gray',
  'gray',
  'black',
  'brown',
  'red',
  'orange',
  'yellow',
  'lime',
  'green',
  'cyan',
  'light_blue',
  'blue',
  'purple',
  'magenta',
  'pink'
];